### ISSUE TITLE
Ошибка на самом последнем этапе

### ISSUE THREAD

**Issue by aliksend** [qrlk/adwhore.net#10]
Доешл до самого конца, нажимаю "отправить", ввожу комментарий о репорте, жму "ОК" и получаю вот это

![изображение](https://user-images.githubusercontent.com/4923699/90695291-d5dedd80-e282-11ea-9b7b-9fe4437aaf99.png)

При повторной попытке получаю то же самое и в консоли браузера и на вкладке Network не вижу сообщений и запросов (при первой попытке не открывал инструменты разработчика)
Ошибка возникает и когда ввожу комментарий и когда оставляю поле пустым

Firefox 79.0 (64-битный), Linux
ADN v0.2

**Comment by qrlk** [comment]
У вас почему-то не создался пользователь, создайте его вручную. 

Эта ошибка встречается у большого количества людей, я пытаюсь понять в чем её проблема.
![image](https://user-images.githubusercontent.com/40423143/90724816-d2217a00-e2c7-11ea-8493-016bc54e9d62.png)
![image](https://user-images.githubusercontent.com/40423143/90724823-d6e62e00-e2c7-11ea-9668-69286aa4cb0d.png)

**Comment by aliksend** [comment]
Спасибо, помогло.
В плане UI/UX есть куда расти во многих места. Желаю удачи с проектом. Возможно помогу в каких-то местах, если будет время
