### ISSUE TITLE
Add new ad skip reason: Not actual advertising

### ISSUE THREAD

**Issue by Perfomer** [qrlk/adwhore.net#33]
Hi there! I want to suggest add one more category: **Not actual advertising**.
I think there's no any reason to see the ad about something not actual, so I want autoskip same ads. 
For example: VK Fest that already was ended.

**Comment by qrlk** [comment]
Hi!
Thanks for the suggestion!  

I agree that it is useless to watch ads not about actual events, but I know that they are extremely rare (I have watched 1.5K segments in the last 2 weeks), and I think that adding such a feature will make it difficult to use the extension.

The category determines the subject / approach of the ad, but not the timing, so I would have to add another checkbox and force the user to check if the subject of the ad is actual or not. I think this will make it harder to use the extension and (worst of all) make the UI much more complex.

Almost all user-submitted segments are from new videos, so someday someone will have to edit a segment to mark it as irrelevant, another person will have to view it ... It's really that difficult. Is it worth it? I don't think so.

It will also confuse the user: for example, [this](https://youtu.be/Um2KEFNgKG0?t=201) is a 1x ad, but the event described in the ad is no longer relevant.
P.S. Festivals are usually recurring events, a promotion / sale is an advertisement for a service / store.
