### ISSUE TITLE
Firefox, Midnight Lizard hides advertisement-bar and skip button (Any known incompatibilitys?)

### ISSUE THREAD

**Issue by Stimmenhotel** [qrlk/adwhore.net#44]
Thanks for this nice piece of software! Even if I normaly just avoid yt-videos with shameless advertisment methods ... I like the idea using it to show other ppl (even if they only use it as adblock) that there is a problem.

Back to my problem:

I have just installed adwhore on my daily browser firefox and submitted a advertisment example for testing the features adwhore is offering. Now ... somehow my firefox is not compatible with adwhore.

While adding a advertisment everything works just fine, but I can't see the "advertisment-bar" within the video, nor the skip button is shown if I reach the submitted advertisment.

I checked my chrome against and it works just fine.

Are there any known incompatibilitys with adwhore?

**Solution**
While writing I just thought about checking back on youtube again and remembered I am using [Midnight Lizard](https://github.com/Midnight-Lizard/Midnight-Lizard) for Websites without a Dark Mode.
It was active for YT and somehow blocked the advertisment-bar and the skip button.
I deactivated it and now it works just fine.

But maybe there is a way to make the two compatible?
I don't know if this something to be fixed on adwhore side or on midnight lizard side, so I just post it here.
If needed, I can post it on Midnight Lizards side to.

**Comment by qrlk** [comment]
Thanks for the details, I was able to figure out what the problem is: everything is pretty trivial.  

At some point, I was faced with the fact that ADN conflicts with YouTube native "yellow" ads. I added a check: to inject segments highlighting and skip them only if the progress bar is red.  

The custom CSS changed the value of the "not advertising" color, so the ADN was behaving incorrectly.

**Comment by qrlk** [comment]
The fix has already been uploaded to AMO, CWS's reviewing changes.

I will try to make the extension completely resistant to css changes in the next version, I wanted to do this for a long time.
