### ISSUE TITLE
Adding three ad segments will result in a overflow

### ISSUE THREAD

**Issue by Stimmenhotel** [qrlk/adwhore.net#45]
I watched a video a few minutes ago and tried to add three ad segemnts to it.
1. a few second "pre-advertisment" about a later insert
2. a advertisment for another video of their channel
3. the advertisment which was announced in 1.

1 & 3 are both "Original insert by blogger", while 2. is "Advertisment of own project".
Testing setting 3. to another type won't change the result.

After describing the ad and pressing "Send", naming the type of ad, instead of a "Sucessfull" I receive:

error
{"error":"overflow"}
error
Conflict

Tried to look into the console of firefox, but I only see the string I named the ad.
Checking adwhore.js I can't find anything about this error either.

**Comment by qrlk** [comment]
This error should occur when the server has found segments in the database, the boundaries of which intersect with the new one.

Are you sure the segments you were trying to send did not overlap?

I am currently rewriting the server, I will double-check if this check is working correctly.

**Comment by Stimmenhotel** [comment]
Ahh ... Thats is why.
Both fragments (2 & 3) indeed overlapped and caused the error. (shifted the third one by +0.1 sec, now it is working)
So the whole "bug" is more about catching this kind of error and telling it to the user.

Thanks for the fast response!

**Comment by qrlk** [comment]
Yes, I saw these three segments when I moderated the database. Skipping them works correctly.

A chain of segments is very rare. This check was conceived to avoid the case when 2 users almost simultaneously mark a segment in the same new video.

The fact that you were confused by this error suggests that I really need to reformulate the error text.

Thank you for bringing this issue to my attention!
