### ISSUE TITLE
Редактирование уже одобренного сегмента

### ISSUE THREAD

**Issue by vladislavke** [qrlk/adwhore.net#51]
Почему бы после высвечивания оценки уже пропущенного сегмента, не добавить кнопку редактировать сегмент?
не все сегменты пропущены идеально, всегда найдутся перфекционисты которые захотят пропустить рекламу кадр в кадр, и при перевале похожих заявок за определённое количество, можно принять усреднённый вариант правок

**Comment by qrlk** [comment]
Извиняюсь, что отвечаю так поздно, был сильно занят в январе и не заметил ваше предложение вовремя.
Крайне некрасиво получилось, особенно если учитывать, что вы зарегистрировались на Github только ради этой issue.

По сути предложения: система замены чужих сегментов [существует с самого начала](https://github.com/qrlk/adwhore.net/wiki/Contributing-%28Russian%29#%D0%B7%D0%B0%D0%BC%D0%B5%D0%BD%D0%B0-%D0%BD%D0%B5%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D0%B5%D0%B3%D0%BC%D0%B5%D0%BD%D1%82%D0%B0), с той лишь разницей, что система даёт вам заменить чужой сегмент только в том случае, если уровень репутации у аккаунта выше, чем у человека, отправившего сегмент. Так же, можно полностью заменить категорию сегмента или просто подкорректировать его границы.

Идея одобрять изменение при перевале похожих заявок неплохая, но на практике она не выдержит вандализма. Я сделаю ставку на активных пользователей, нежели на массу заявок из неизвестных источников.

В прототипе интерфейс всего этого выглядит неудобно и неочевидно, постараюсь с этим что-нибудь сделать.
