### ISSUE TITLE
Расширение перестало работать.

### ISSUE THREAD

**Issue by pozitronik** [qrlk/adwhore.net#52]
С какого-то из последних апдейтов Fx Nightly значок расширения пропал из ютубовского плеера. Свои скипы поставить нельзя, чужие скипы тоже не показываются.
В списке расширений AWN есть, форма настройки работает, как должно.
Пробовал переустанавливать расширение - не помогло.
В консольке расширение доходит до ADN's ready', никаких проблем не вижу.
Другие расширения иконки рисуют без проблем. Пробовал все их отключать, во избежание конфликтов, - не помогает.

Создал новый пустой профиль, поставил туда расширение - заработало.
Текущая версия браузера - 90.0a1

Куда копать?

![изображение](https://user-images.githubusercontent.com/2357892/118792331-3c3f6d80-b8a0-11eb-8c9c-17cbd6a36681.png)

**Comment by qrlk** [comment]
Привет, спасибо за репорт.
Хоть проект и выглядит заброшенным, я до сих пор жив и работаю над его реинкарнацией в свободное время.

Со своей стороны я не смог воспроизвести проблему с отсутствием интерфейса =(
На последней версии Nightly (с пустым профилем) интерфейс функционирует нормально, как и в случае с другими браузерами у нескольких пользователей.

В последних апдейтах Nightly я не нашел ничего такого, что могло бы сильно повлиять на работу расширения. В [These Weeks in Firefox: Issue 92](https://blog.nightly.mozilla.org/2021/04/26/these-weeks-in-firefox-issue-92/) от 26.04 есть упонимание о фиксе бага, который блокировал запросы к разрешенным в манифесте файлам расширения. Консоль ругается на какой-то запрос сразу же после того, как расширение пытается получить html оверлея из файла, указанного в web_accessible_resources.
![image](https://user-images.githubusercontent.com/40423143/118809055-ce507180-b8b2-11eb-9848-45ef8aec14f5.png)

Насколько я помню найтли обновляется каждый день и фикс был уже давно, но всё же я бы проверил какая именно стоит версия в "меню - справка - о Nightly". Как я понял, по текущей версии браузера можно мало что сказать, важна именно дата билда. 90.0a1 появилась 19.04, блог пост с сообщение о фиксе бага появился 26.04.
![image](https://user-images.githubusercontent.com/40423143/118810397-83375e00-b8b4-11eb-893e-d1ed4d2952d4.png)

P.S. Попутно я обнаружил, что сильно облажался с backend'ом как раз несколько дней назад, что сломало добавление новых сегментов, а может быть и ещё что-то. Вряд ли проблема интерфейса связана с этим, но исправление сломанного основного функционала сейчас в абсолютном приоритете!

**Comment by pozitronik** [comment]
Билды всегда актуальные, конкретно сейчас 2021-05-18.
Но с какого билда началась проблема - не знаю.
Напомню, что в том же браузере, но в новом профиле, ADW работает.
Я пробовал вычищать все расширения из профиля, убивал каталоги расширений, файлы их настроек, переставлял наново - не помогло.
Я протрейсил исполнение расширения, насколько могу судить - элементы создаются, оверлей инжектится, никаких ошибок, но просто ничего нет =).
Если есть мысли, что стоит проверить - проверю.

**Comment by qrlk** [comment]
А что, если открыть видео, на котором гарантированно есть реклама?

![image](https://user-images.githubusercontent.com/40423143/118827812-69524700-b8c5-11eb-8553-872ed6f04df0.png)

[ссылка на шедевр нативной интеграции](https://www.youtube.com/watch?v=lvJTg8HNHO0&t=20s) 

P.S. Я обновил DNS час назад, сначала нужно проверить, что по karma.adwhore.net пингуется 165.227.133.104

**Comment by qrlk** [comment]
Ещё идея: ошибки расширений не выводятся в консоль Dev Tools, а в https://developer.mozilla.org/ru/docs/Tools/Browser_Console

**Comment by pozitronik** [comment]
>
>А что, если открыть видео, на котором гарантированно есть реклама, которая гарантированно пропустится сама?

Старый профиль - не пропускается.
Новый профиль - пропускается.

>
>karma.adwhore.net пингуется 165.227.133.104

Да.

> 
> 
> Ещё идея: ошибки расширений не выводятся в консоль Dev Tools, а в https://developer.mozilla.org/ru/docs/Tools/Browser_Console

Да, хорошая зацепка:
![изображение](https://user-images.githubusercontent.com/2357892/118838119-192bb280-b8ce-11eb-807d-3f346769a0c3.png)

В "чистом" профиле эти ошибки тоже сыпятся, но выполнение доходит до XHR-запроса к karma.adwhore.net

![изображение](https://user-images.githubusercontent.com/2357892/118839277-0cf42500-b8cf-11eb-810c-36d2f887570d.png)

В стабильной сборке Fx этих ошибок нет, только запросы
![изображение](https://user-images.githubusercontent.com/2357892/118839570-44fb6800-b8cf-11eb-8644-844addec5f21.png)

**Comment by pozitronik** [comment]
Кажется, нашёл, от чего можно копать.
Попробовал временно пересесть на стабильную сборку Fx, чисто ради AWN.
Установил все нужные расширения, AWN в т.ч., попробовал поставить скипы - работает.
Залогинился в youtube - интерфейс расширения пропал.
Разлогинился - всё заработало.

Попробовал разлогиниться из аккаунта в nightly - интерфейс появился. Залогинился - исчез.

**Comment by qrlk** [comment]
У меня была такая мысль, но почему-то подумал, что на всех инстансах браузера один и тот же аккаунт гугла.

Такое случалось и раньше у моего знакомого, но я не придал этому особого значения, потому что знакомый не планировал использовать расширение и у него могли быть конфликты с другими расширениями.

Возможно ютуб случайным образом выбирает небольшие группы людей и даёт им какую-то особую версию фронта. Шиза какая-то. Завтра попробую связаться с этим человеком и воспроизвести проблему.

**Comment by pozitronik** [comment]
>Возможно ютуб случайным образом выбирает небольшие группы людей и даёт им какую-то особую версию фронта

А вот да. Залогинился под вторым аккаунтом - всё ок.

**Comment by qrlk** [comment]
Получилось воспроизвести проблему у знакомого, а так же на одном из своих старых гуглоаккаунтов.
Посмотрю что можно сделать.

**Comment by qrlk** [comment]
https://github.com/qrlk/adwhore.net/commit/bd9d7b05f8fa92bb01566668206d20134bb0ed9e

https://github.com/qrlk/adwhore.net/archive/refs/heads/develop.zip

Работает?

**Comment by qrlk** [comment]
https://github.com/qrlk/adwhore.net/commit/ce6d9eb98c928cc175143aba8b1606a05a73ed52

https://github.com/qrlk/adwhore.net/archive/refs/heads/develop.zip

Работает?

**Comment by pozitronik** [comment]
А как собрать из исходников расширение?
Если сделать xpi из src архива заменой файлов внутри, то
![изображение](https://user-images.githubusercontent.com/2357892/119093326-45ebe100-ba18-11eb-8e19-d241d2e58382.png)
(и в Nightly и в stable).

**Comment by qrlk** [comment]
`about:debugging#/runtime/this-firefox` -> загрузить временное дополнение -> клик по манифесту

**Comment by pozitronik** [comment]
👍 подхватилось, заработало.

**Comment by qrlk** [comment]
Залил апдейт, в хром сторе на проверке, фф уже принял. Позже перепишу все места, где задействован дом ютуба.

Самое неприятное, что эта ошибка в Firefox просто не выводилась ни в лог браузера, ни в консоль. В хроме всё было очевидно.

Ещё раз спасибо.

**Comment by pozitronik** [comment]
Вам спасибо.
